import argparse
import csv
import json
from pathlib import Path


# 真机结果对比脚本：把本源云 counts 和本地 statevector 理论概率逐项对齐。
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--counts", required=True, help="JSON file like {\"0011\": 230, \"0110\": 210}.")
    parser.add_argument("--reference", required=True, help="Reference CSV generated by export_hardware_qasm.py.")
    parser.add_argument("--top", type=int, default=8)
    parser.add_argument(
        "--bit-order",
        choices=["qiskit", "selection"],
        default="qiskit",
        help="Use qiskit if hardware counts keys match qiskit_bitstring; use selection if keys match selection.",
    )
    return parser.parse_args()


def load_reference(path):
    # reference.csv 来自 export_hardware_qasm.py，包含两种 bitstring 顺序。
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append({
                "rank": int(row["rank"]),
                "selection": row["selection"],
                "qiskit_bitstring": row["qiskit_bitstring"],
                "probability": float(row["probability"]),
            })
    return rows


def load_counts(path):
    # 支持两种输入：纯 counts dict，或 submit_originq_job.py 保存的完整任务 JSON。
    with open(path, encoding="utf-8") as f:
        raw = json.load(f)
    if isinstance(raw, dict) and "counts" in raw:
        raw = raw["counts"]
    return {str(key): int(value) for key, value in raw.items()}


def main():
    args = parse_args()
    reference = load_reference(Path(args.reference))
    counts = load_counts(Path(args.counts))
    shots = sum(counts.values())
    # 不同平台可能用不同 bit 顺序显示结果，因此提供 qiskit/selection 两种匹配方式。
    key_field = "qiskit_bitstring" if args.bit_order == "qiskit" else "selection"

    print("shots:", shots)
    print("bit_order:", args.bit_order)
    print("rank\tselection\tkey\ttheory_p\thardware_p\tdelta")
    for row in reference[:args.top]:
        key = row[key_field]
        hardware_p = counts.get(key, 0) / shots if shots else 0.0
        delta = hardware_p - row["probability"]
        print("{}\t{}\t{}\t{:.6f}\t{:.6f}\t{:+.6f}".format(
            row["rank"],
            row["selection"],
            key,
            row["probability"],
            hardware_p,
            delta,
        ))


if __name__ == "__main__":
    main()
